### ISSUE TITLE
elsaticsearch-master Instance getting failed when deploying graylog bosh-release

### ISSUE THREAD

**Issue by saratkumar123** [AusDTO/graylog-boshrelease#13]
Hello Team,  I am encountering an error when deploying Graylog on our opensource CF platform (Azure IAAS). I am trying to deploy Graylog with Bosh-release.
Graylog project --   https://github.com/govau/graylog-boshrelease
I have deployed latest release graylog v0.2.0
Used below stemcell
stemcells:
- alias: default
  os: ubuntu-xenial
  version: 621.123
After bosh deploy, The "elasticsearch-master" getting failed with below errors.
It's been 3 days I got stuck with this issue. Can someone please assist me on this. Many thanks!!

/var/vcap/sys/log/elsaticsearch/elasticsearch.stderr.log

**Exception in thread "main" SettingsException[Failed to open stream for url [/var/vcap/packages/elasticsearch/config/elasticsearch.yml]]; nested: AccessDeniedException[/var/vcap/packages/elasticsearch/config/elasticsearch.yml];
Likely root cause: java.nio.file.AccessDeniedException: /var/vcap/packages/elasticsearch/config/elasticsearch.yml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1067)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:88)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
        at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:242)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Refer to the log for complete error details.**

![image](https://user-images.githubusercontent.com/56149476/120588540-fb755600-c454-11eb-97c6-1eab23acbfa3.png)
![image](https://user-images.githubusercontent.com/56149476/120588577-0af49f00-c455-11eb-8062-441198af9331.png)

**Comment by shivsepra** [comment]
@saratkumar123 
I don't think there is permission to access files in the package folder.
Ideally, the elasticsearch.yml file should be present in /var/vcap/jobs/elasticsearch/config folder.
Could check which config file is being used in /var/vcap/jobs/elasticsearch/bin/ctl file
